sudo: required
language: generic

services:
  - docker

before_install:
  -  docker build -t masumahmedeesha/docker-kubernetes-react -f Dockerfile.dev .

script:
  - docker run -e CI=true masumahmedeesha/docker-kubernetes-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-640324462641"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY